export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const BUY_PRODUCTS = 'BUY_PRODUCTS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const PRODUCT_DETAIL = 'PRODUCT_DETAIL';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';





// Create action types for CRUD operations
// export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
// export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE';
// export const READ_ITEM_SUCCESS = 'READ_ITEM_SUCCESS';
// export const READ_ITEM_FAILURE = 'READ_ITEM_FAILURE';
// export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
// export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';
// export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
// export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';
